[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip = [".mypy_cache", ".pytest_cache" , "venv", "./venv", "azure-pipelines.yml"]

[tool.black]
line-length = 120
verbose = 1
color = true
exclude = [".mypy_cache", ".pytest_cache" , "venv", "./venv", "azure-pipelines.yml"]

[tool.flake8]
max-line-length = 120
rst-roles = "class, func, ref"
rst-directives = "envvar, exception"
extend-ignore = "E203,E501,W503,D100,D105,D107,D400,D104,F401,DAR401"
docstring-convention = "pep257"
exclude=".git,./venv,./build,azure-pipelines-previously.yml,azure-pipelines.yml"
docstring_style = "sphinx"
