image: ${REGISTRY}/way1k-automation-group/test_framework/image:${COMMIT_REF_NAME}

stages:
  - test

.regular-runs-base:
  stage: test
  tags:
    - common-255
  rules:
#    - if: '($PIPELINE_SOURCE == "merge_request_event" || $PIPELINE_SOURCE == "push") && $MARK_NAMES == "None"'
    - if: '$CI_MERGE_REQUEST_ID && $MARK_NAMES == "None"'
      when: manual
      allow_failure: true

### Test stage jobs for Bashorg ###

api-bashorg:
  extends: .regular-runs-base
  script:
    - pytest -v tests/bashorg/api --env=$ENVIRONMENT --browser=$BROWSER --browser_version=$BROWSER_VERSION --report=yes --log_level=DEBUG

ui-bashorg:
  extends: .regular-runs-base
  script:
    - pytest -v tests/bashorg/ui --env=$ENVIRONMENT --browser=$BROWSER --browser_version=$BROWSER_VERSION --report=yes